### ISSUE TITLE
How to load Playlist from json file on app start up

### ISSUE THREAD

**Issue by inglesuniversal** [expo/playlist-example#10]
Wonderful example. Is there a way to load a json file that can be imported and fetched in at the time the user opens the app to get a fresh and updated list of streams? I would appreciate if you can give me some pointers on how to accomplish that. Thanks and great work!

**Comment by cruzach** [comment]
Not 100% sure if this is what you're looking for, but I think the `componentDidMount` lifecycle hook is what you're looking for
