### ISSUE TITLE
Playlist stops when put into the background

### ISSUE THREAD

**Issue by hounsellal** [expo/playlist-example#11]
Great example. Only problem is that the playlist stops when you put the app into the background. Any idea on how to get it to keep playing the current item, AND advance to the next item all while in the background?

**Comment by chrisheninger** [comment]
According to https://docs.expo.io/versions/latest/sdk/audio.html:

> Note that Expo does not yet support backgrounding, so audio is not available to play in the background of your experience. Audio also automatically stops if headphones / bluetooth audio devices are disconnected.

**Comment by cruzach** [comment]
You can use the [`staysActiveInBackground`](https://docs.expo.io/versions/latest/sdk/audio/#arguments-1) argument for `Audio.setAudioModeAsync(mode)`
