### ISSUE TITLE
How to play audio file as soon as screen is loaded

### ISSUE THREAD

**Issue by inglesuniversal** [expo/playlist-example#13]
Hi, is there a way to play a local bundled audio file as soon as the component is loaded or rendered?

similar to <body onload=",,,"> on html

So that it is played as an intro sound without any required interaction from the user.

Thanks

**Comment by jorgegorka** [comment]
You just need to update the componentDidMount event to load the file and play it.

```
componentDidMount() {
  (async () => {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
      playsInSilentModeIOS: true,
      shouldDuckAndroid: true,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
    });
    await this._updatePlaybackInstanceForIndex(playing);
    this._onPlayPausePressed();
    
  })();  
  (async () => {
    await Font.loadAsync({
      'cutive-mono-regular': require('./assets/fonts/CutiveMono-Regular.ttf'),
    });
    this.setState({ fontLoaded: true });
  })();
}
```

**Comment by Gitsanto** [comment]
I changed it but it says "Can't find variable:playing" 

![img_269c570e34c0-1](https://user-images.githubusercontent.com/8325731/37748455-45c0bfb0-2dc7-11e8-995b-38bab0bc9c10.jpeg)

**Comment by cruzach** [comment]
Hey, late follow-up here but I suggest going through the [Audio documentation](https://docs.expo.io/versions/latest/sdk/audio/) to see the best way of doing this
