### ISSUE TITLE
can't read .wav file

### ISSUE THREAD

**Issue by Nermin-K** [expo/playlist-example#17]
@brentvatne  I generate this (.wav) audio file [https://drive.google.com/file/d/1yXmoV6tk30n4klJFtzA8-t4DLtGgkJwh/view](url) using C# code. when I try to play it using `Expo.Audio.Sound.create(require('./GUIdump.wav')` but I can't hear any voice and I got no errors just this warning [https://drive.google.com/file/d/1pm0Uwe-xLaEFAY_BtvgXFoe9V4snYqTG/view?usp=sharing](url)

**Comment by cruzach** [comment]
If you have this error now using SDK 34, let me know and I'll reopen
